name: 'Deploy to environment'
description: 'Deploys the application to the hosted environment'
inputs:
  app-artifact-name:
    required: true
  azure-static-web-apps-api-token:
    required: true
runs:
  using: "composite"
  steps:

      - name: Download Publish Artifact
        uses: actions/download-artifact@v4
        with:
         name: ${{ env.APP_ARTIFACT_NAME }}
         path: artifacts/${{ inputs.app-artifact-name }}

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ inputs.azure-static-web-apps-api-token }}
          action: 'upload'
          app_location: artifacts/${{ inputs.app-artifact-name }}
          output_location: ''
          skip_app_build: true
